import React, { useState } from "react";
import PaymentVoucher from "../../Forms/widgets/PaymentVoucher";
import StoreReceiptVoucher from "../../Forms/widgets/StoreReceiptVoucher";
import StoreIssueVoucher from "../../Forms/widgets/StoreIssueVoucher";
import ProcurementOrder from "../../Forms/widgets/ProcurementOrder";
import JobMaintenanceRequisition from "../../Forms/widgets/JobMaintenanceRequisition";
import DutyTourExpense from "../../Forms/widgets/DutyTourExpense";
import ClaimOutOfPocketExpense from "../../Forms/widgets/ClaimOutOfPocketExpenses";
import RequestForPurchaseOrSpecialAdvance from "../../Forms/widgets/RequestForPurchaseOrSpecialAdvance";
import PaymentVoucherTetfund from "../../Forms/widgets/PaymentVoucher-Tetfund";
import PaymentVoucherAuto from "../../Forms/widgets/PaymentVoucher-auto";
import AnnualLeaveResumptionOfDuty from "../../Forms/widgets/AnnualLeaveResumptionOfDuty";
import RequestForLeave from "../../Forms/widgets/RequestForLeave";
import StaffIdCardDataForm from "../../Forms/widgets/StaffIdCardDataForm";
import EmployeeDisengagementForm from "../../Forms/widgets/EmployeeDisengagementForm";
import PromotionInterestForm from "../../Forms/widgets/PromotionInterestForm";
import ChangeOfNextOfKinForm from "../../Forms/widgets/ChangeOfNextOfKinForm";

export interface FormProps {
  id: string | number;
  name: string;
  description: string;
  status: string;
  createdBy: string;
  lastUpdated: string;
  workflows: string[];
  component: React.FC<any>;
  inputLabels: { [key: string]: string }; // Added inputLabels property
  assigneeHolders: { [key: string]: string };
  formSections: { [key: string]: string };
  splitApprovalMarker?: string[];
}

const useForm = () => {
  const [forms, setForms] = useState<any[]>([
    {
      id: 1,
      name: "Payment Voucher Auto",
      description: "Employee leave request form with date selection and reason",
      status: "Active",
      createdBy: "Finance",
      lastUpdated: "2024-01-10",
      workflows: ["Financial Request"],
      component: (props: any) => <PaymentVoucherAuto {...props} />,
      inputLabels: {
        applicantName: "Name",
        applicantAddress: "Address",
        applicantDescription: "Request detail",
        paymentDate: "Payment Date",
        paymentParticles: "Particlars (Including References)",
        paymentDetailAmount: "Payment Detail Amount",
        amountInWord: "Amount in words",
        accountTitle: "Account Title",
        accountCodeNo: "Account Code No.",
        debitAmount: "Debit Amount",
        debitDescription: "Debit Description",
        creditAmount: "Credit Amount",
        creditDescription: "Credit Description",

        unitVoucherHeadById: "Head of Unit [Voucher]",
        preparedById: "Voucher Prepared By",
        reviewedById: "Voucher Reviewed By",
        approvedById: "Voucher Approved By",

        auditRemarkPass: "Audit Remark Pass",
        auditCheckedById: "Audit Checked by",
        auditCheckedByDate: "Audig Checked Date",
        auditRemarkQuery: "Audit Query",
        auditPreparedById: "Audit Prepared By",
        auditPreparedByDate: "Audit Prepared By Date",
        auditReviewedById: "Audit Reviewed By",
        auditReviewedByDate: "Audit Reviewed By Date",
        auditRemarkedById: "Audit Remarked By",
        auditApprovedByDate: "Audit Remarked By Date",

        cpoHeadById: "CPO Head of Unit",
        cpoPreparedById: "CPO Creator",
        cpoReviewedById: "CPO Reviewer",
        cpoApprovedById: "CPO Approver",

        additionalNotes: "Additional Notes",

        schoolDeanById: "School Dean",
        departmentHeadById: "Department Head",
        chiefExecutivedById: "Chief Executive",
      },
      assigneeHolders: {
        schoolDeanId: "School Dean",
        departmentHeadById: "Head of Department",
        unitVoucherHeadById: "Head of Unit [Voucher]",
        preparedById: "Voucher Prepared By",
        reviewedById: "Voucher Reviewed By",
        approvedById: "Voucher Approved By",
        auditCheckedById: "Audit Checked by",
        auditPreparedById: "Audit Prepared By",
        auditReviewedById: "Audit Reviewed By",
        auditRemarkedById: "Audit Approved By",
        cpoHeadById: "CPO Head of Unit",
        cpoPreparedById: "CPO Creator",
        cpoReviewedById: "CPO Reviewer",
        cpoApprovedById: "CPO Approver",
        schoolDeanById: "School Dean",
      },
      formSections: {
        showFormTitle: "Voucher Title",
        showApplicationFormTitle: "Application Title",
        instruction: "Instruction",
        applicantInformation: "Applicant Information",
        paymentDetails: "Payment Voucher Details",
        entryDistribution: "Entry Distribution",
        voucherApproval: "Voucher Approval",
        cpoApproval: "Central Payment Office",
        auditApproval: "Audit Approval",
        additionalInformation: "Additional Information",
        audit: "Audit Unit",
        fundAndManagement: "Fund and Management",
        approvals: "Approvals",
        showActionButtons: "Action buttons",
      },
    },
    {
      id: 2,
      name: "Store Receipt Voucher",
      description: "Please receive into Store the undermentioned stores",
      status: "Active",
      createdBy: "Store",
      lastUpdated: "2024-01-10",
      workflows: ["Store Receipt Voucher"],
      component: (props: any) => <StoreReceiptVoucher {...props} />,
      inputLabels: {
        voucherNo: "Voucher number",
        voucherDate: "Voucher Date",
        toTheCentralStores: "To The Central Stores",
        nameOfSupplier: "Name of Supplier",
        supplierAddress: "Supplier Address",
        articles: "Articles",
        denominationOfQty: "Denomination of Qty",
        qtyReceived: "Quantity Received",
        unitPrice: "Unit Price",
        amount: "Amount",
        ledgerFolio: "Ledger Folio",
      },
      assigneeHolders: {},
      formSections: {
        addMore: "Add more button",
      },
    },
    {
      id: 3,
      name: "Store Issue Voucher",
      description: "",
      status: "Active",
      createdBy: "Store",
      lastUpdated: "2024-01-10",
      workflows: ["Store Issue Voucher"],
      component: (props: any) => <StoreIssueVoucher {...props} />,
      inputLabels: {
        unit: "Unit/Department/School",
        applicationDate: "Application Date",
        sivNo: "SIV No",
        department: "Department",
        issueAuthoriseBy: "Issue Authorise By",
        designation: "Designation",
        articles: "Articles",
        denominationOfQty: "Denomination of Quantity",
        qtyDemanded: "Quantity Demanded",
        qtyIssued: "Quantity Issued",
        rate: "rate",
        amount: "amount",
        ledgerFolio: "Ledger Folio",
        remarks: "Remarks",
      },
      assigneeHolders: {},
      formSections: {
        addMore: "Add more button",
      },
    },
    {
      id: 4,
      name: "Procurement Order",
      description: "",
      status: "Active",
      createdBy: "Store",
      lastUpdated: "2024-01-10",
      workflows: ["Procurement Request"],
      component: (props: any) => <ProcurementOrder {...props} />,
      inputLabels: {
        requestorDeligation: "Department/School/Unit",
        itemName: "Item name",
        quantity: "Item quantity",
        additionalNotes: "Additional notes",
      },
      assigneeHolders: {},
      formSections: {
        addMore: "Add more button",
      },
      splitApprovalMarker: ["Approve for payment", "Approve for procurement"],
    },
    {
      id: 5,
      name: "Job/Maintenance Requisition",
      description: "",
      status: "Active",
      createdBy: "Store",
      lastUpdated: "2024-01-10",
      workflows: ["Procurement Request"],
      component: (props: any) => <JobMaintenanceRequisition {...props} />,
      inputLabels: {
        requestorDeligation: "Department/School/Unit",
        date: "Date",
        location: "Location",
        recommendationNotes: "Recommendation Notes",
        description: "description",
      },
      assigneeHolders: {},
      formSections: {},
    },
    {
      id: 6,
      name: "Payment Voucher",
      description:
        "Employee finance request form with date selection and reason",
      status: "Active",
      createdBy: "Finance",
      lastUpdated: "2024-01-10",
      workflows: ["Financial Request"],
      component: (props: any) => <PaymentVoucher {...props} />,
      inputLabels: {
        applicantName: "Name",
        applicantAddress: "Address",
        applicantDescription: "Request detail",

        paymentDate: "Payment Date",
        paymentParticles: "Particlars (Including References)",
        paymentDetailAmount: "Payment Detail Amount",
        amountInWord: "Amount in words",
        accountTitle: "Account Title",
        accountCodeNo: "Account Code No.",
        debitAmount: "Debit Amount",
        debitDescription: "Debit Description",
        creditAmount: "Credit Amount",
        creditDescription: "Credit Description",

        unitVoucherHeadById: "Head of Unit [Voucher]",
        preparedById: "Voucher Prepared By",
        reviewedById: "Voucher Reviewed By",
        approvedById: "Voucher Approved By",

        auditRemarkPass: "Audit Remark Pass",
        auditCheckedById: "Audit Checked by",
        auditCheckedByDate: "Audig Checked Date",
        auditRemarkQuery: "Audit Query",
        auditPreparedById: "Audit Prepared By",
        auditPreparedByDate: "Audit Prepared By Date",
        auditReviewedById: "Audit Reviewed By",
        auditReviewedByDate: "Audit Reviewed By Date",
        auditRemarkedById: "Audit Remarked By",
        auditApprovedByDate: "Audit Remarked By Date",

        cpoHeadById: "CPO Head of Unit",
        cpoPreparedById: "CPO Creator",
        cpoReviewedById: "CPO Reviewer",
        cpoApprovedById: "CPO Approver",

        additionalNotes: "Additional Notes",

        schoolDeanById: "School Dean",
        departmentHeadById: "Department Head",
        chiefExecutivedById: "Chief Executive",
      },
      assigneeHolders: {
        schoolDeanId: "School Dean",
        departmentHeadById: "Head of Department",
        unitVoucherHeadById: "Head of Unit [Voucher]",
        preparedById: "Voucher Prepared By",
        reviewedById: "Voucher Reviewed By",
        approvedById: "Voucher Approved By",
        auditCheckedById: "Audit Checked by",
        auditPreparedById: "Audit Prepared By",
        auditReviewedById: "Audit Reviewed By",
        auditRemarkedById: "Audit Approved By",
        cpoHeadById: "CPO Head of Unit",
        cpoPreparedById: "CPO Creator",
        cpoReviewedById: "CPO Reviewer",
        cpoApprovedById: "CPO Approver",
        schoolDeanById: "School Dean",
      },
      formSections: {
        showFormTitle: "Voucher Title",
        showApplicationFormTitle: "Application Title",
        instruction: "Instruction",
        applicantInformation: "Applicant Information",
        paymentDetails: "Payment Voucher Details",
        entryDistribution: "Entry Distribution",
        voucherApproval: "Voucher Approval",
        cpoApproval: "Central Payment Office",
        auditApproval: "Audit Approval",
        additionalInformation: "Additional Information",
        audit: "Audit Unit",
        fundAndManagement: "Fund and Management",
        approvals: "Approvals",
        showActionButtons: "Action buttons",
      },
    },
    {
      id: 7,
      name: "Duty Tour Expense Form",
      description: "",
      status: "Active",
      createdBy: "Bursar",
      lastUpdated: "2024-01-10",
      workflows: ["Finance Request"],
      component: (props: any) => <DutyTourExpense {...props} />,
      inputLabels: {
        officerName: "Name of Officer",
        phone: "Phone number",
        rank: "Rank",
        contedisConpcass: "CONTEDISS/CONPCASS",
        purpose: "Purpose of Tour",
        travelLocation: "Place(s) of travel",
        startDate: "Period of Tour [Start Date]",
        endDate: "Period of Tour [End Date]",
        travelMode: "Tranport mode specify",
        estimatedTransportCost: "Estimated Transport Cost",
        estimatedNight: "Estimated Night Allowance",
        others: "Other(s) (If Applicable) Specify",
        totalEstimate: "Total",
        totalInWord: "Total in words",
        bank: "Bank",
        accountNumber: "Account number",
        amountApproveFigure: "Sum of amount (in figure)",
        amountApproveWord: "Approve amount (in word)",
      },
      assigneeHolders: {},
      formSections: {},
    },
    {
      id: 8,
      name: "Claim Form for Out-of-Pocket Expenses",
      description: "",
      status: "Active",
      createdBy: "Bursar",
      lastUpdated: "2024-01-10",
      workflows: ["Finance Request"],
      component: (props: any) => <ClaimOutOfPocketExpense {...props} />,
      inputLabels: {
        officerName: "Officer Name",
        department: "Department",
        amount: "Amount",
        amountInWord: "Amount in word",
        purpose: "Purpose as follows",
        noReceiptAttestation: "No Receipt Attestation",
        bank: "Bank",
        accountNumber: "Account number",
      },
      assigneeHolders: {},
      formSections: {},
    },
    {
      id: 9,
      name: "Request for Purchase or Special Advance",
      description: "",
      status: "Active",
      createdBy: "Bursar",
      lastUpdated: "2024-01-10",
      workflows: ["Finance Request"],
      component: (props: any) => (
        <RequestForPurchaseOrSpecialAdvance {...props} />
      ),
      inputLabels: {
        officerName: "Name of Officer",
        rank: "Rank",
        contiss: "CONTISS",
        compNo: "COMP No",
        purpose: "Purpose of Advance",
        bank: "Bank",
        accountNumber: "Account number",
        outstandingBalance: "Outstanding Balance yet to be retired",
        advanceAmount: "Amount of Advance Required",
        totalInWord: "totalInWord",
        unitVoucherHeadById: "Voucher Head of Unit",
      },
      assigneeHolders: {},
      formSections: {},
    },
    {
      id: 10,
      name: "Payment Voucher (TETFund)",
      description: "Form for TETFund payment vouchers",
      status: "Active",
      createdBy: "Finance",
      lastUpdated: "2024-01-10",
      workflows: ["Financial Request"],
      component: (props: any) => <PaymentVoucherTetfund {...props} />,
      inputLabels: {
        applicantName: "Name",
        applicantAddress: "Address",
        applicantDescription: "Request detail",

        paymentDate: "Payment Date",
        paymentParticles: "Particlars (Including References)",
        paymentDetailAmount: "Payment Detail Amount",
        amountInWord: "Amount in words",
        accountTitle: "Account Title",
        accountCodeNo: "Account Code No.",
        debitAmount: "Debit Amount",
        debitDescription: "Debit Description",
        creditAmount: "Credit Amount",
        creditDescription: "Credit Description",

        unitVoucherHeadById: "Head of Unit [Voucher]",
        preparedById: "Voucher Prepared By",
        reviewedById: "Voucher Reviewed By",
        approvedById: "Voucher Approved By",

        auditRemarkPass: "Audit Remark Pass",
        auditCheckedById: "Audit Checked by",
        auditCheckedByDate: "Audig Checked Date",
        auditRemarkQuery: "Audit Query",
        auditPreparedById: "Audit Prepared By",
        auditPreparedByDate: "Audit Prepared By Date",
        auditReviewedById: "Audit Reviewed By",
        auditReviewedByDate: "Audit Reviewed By Date",
        auditRemarkedById: "Audit Remarked By",
        auditApprovedByDate: "Audit Remarked By Date",

        cpoHeadById: "CPO Head of Unit",
        cpoPreparedById: "CPO Creator",
        cpoReviewedById: "CPO Reviewer",
        cpoApprovedById: "CPO Approver",

        additionalNotes: "Additional Notes",

        schoolDeanById: "School Dean",
        departmentHeadById: "Department Head",
        chiefExecutivedById: "Chief Executive",
      },
      assigneeHolders: {
        schoolDeanId: "School Dean",
        departmentHeadById: "Head of Department",
        unitVoucherHeadById: "Head of Unit [Voucher]",
        preparedById: "Voucher Prepared By",
        reviewedById: "Voucher Reviewed By",
        approvedById: "Voucher Approved By",
        auditCheckedById: "Audit Checked by",
        auditPreparedById: "Audit Prepared By",
        auditReviewedById: "Audit Reviewed By",
        auditRemarkedById: "Audit Approved By",
        cpoHeadById: "CPO Head of Unit",
        cpoPreparedById: "CPO Creator",
        cpoReviewedById: "CPO Reviewer",
        cpoApprovedById: "CPO Approver",
        schoolDeanById: "School Dean",
      },
      formSections: {
        showFormTitle: "Voucher Title",
        showApplicationFormTitle: "Application Title",
        instruction: "Instruction",
        applicantInformation: "Applicant Information",
        paymentDetails: "Payment Voucher Details",
        entryDistribution: "Entry Distribution",
        voucherApproval: "Voucher Approval",
        cpoApproval: "Central Payment Office",
        auditApproval: "Audit Approval",
        additionalInformation: "Additional Information",
        audit: "Audit Unit",
        fundAndManagement: "Fund and Management",
        approvals: "Approvals",
        showActionButtons: "Action buttons",
      },
    },

    {
      id: 11,
      name: "Annual Leave Resumption of Duty Form",
      description: "",
      status: "Active",
      createdBy: "System",
      lastUpdated: "2024-01-10",
      workflows: ["General Request"],
      component: (props: any) => <AnnualLeaveResumptionOfDuty {...props} />,
      inputLabels: {
        leaveType: "Leave Type",
        leaveTypeOther: "Leave Type Other",
        officerName: "Officer Name",
        phoneNo: "Phone Number",
        department: "Department",
        rank: "Rank",
        unit: "Unit",
        departureDate: "Departure Date",
        resumptionDate: "Resumption Date",
        comments: "Comments",
      },
      assigneeHolders: {},
      formSections: {},
    },
    {
      id: 12,
      name: "Request for Annual/Casual/Maternity Leave",
      description: "",
      status: "Active",
      createdBy: "System",
      lastUpdated: "2025-02-01",
      workflows: ["General Request"],
      component: (props: any) => <RequestForLeave {...props} />,
      inputLabels: {
        leaveType: "Leave Type",
        officerName: "Officer Name",
        department: "Department",
        unit: "Unit",
        rank: "Rank/Position",
        levelSteps: "CONPCASS/CONTEDISS Level",
        numberOfDays: "Number of Days Desired",
        leaveYear: "Leave Year",
        commencementDate: "Date of Commencement",
        phoneNumber: "Phone Number",
        addressOnLeave: "Address while on Leave",
        hodRelease: "HOD Release",
        hodComments: "HOD Comments",
        hodName: "HOD Name",
        deanName: "Dean Name",
        deanDesignation: "Dean Designation",
        registrarApprovalDate: "Registrar Approval Date",
        approvedDepartureDate: "Approved Departure Date",
        leaveEntitlement: "Leave Entitlement",
        deductionFromLeave: "Deduction from Leave",
        balanceFromLeave: "Balance from Leave",
        totalDeferredLeave: "Total Deferred Leave",
        dateReturning: "Date Returning",
      },
      assigneeHolders: {
        departmentHeadById: "Head of Department/Unit",
        schoolDeanById: "School Dean",
        personnelOfficerById: "Personnel Affairs Officer",
        registrarById: "Registrar/Provost"
      },
      formSections: {
        sectionA: "Section A: Applicant",
        sectionB: "Section B: HOD",
        sectionC: "Section C: Dean",
        sectionD: "Section D: Registrar/Provost",
        sectionE: "Section E: Personnel Affairs",
      },
    },
    {
      id: 13,
      name: "Staff Identity Card Data Form",
      description: "Form for requesting Staff ID Card (New, Promotion, or Loss)",
      status: "Active",
      createdBy: "System",
      lastUpdated: "2025-02-01",
      workflows: ["General Request"],
      component: (props: any) => <StaffIdCardDataForm {...props} />,
      inputLabels: {
        fileNo: "File No",
        surnameFirst: "Name (Surname First)",
        department: "Department",
        dob: "Date of Birth",
        sex: "Sex",
        computerNo: "Computer No",
        phoneNo: "Phone No",
        rank: "Present Rank",
        designation: "Designation",
        dateOfAppointment: "Date of Appointment",
        permanentAddress: "Permanent Address",
        reasonNewStaff: "New Staff",
        reasonPromotion: "Promotion",
        reasonLoss: "Loss",
        nextOfKinNameAddress: "Next of Kin Name & Address",
        nextOfKinPhone: "Next of Kin Phone",
        verifiedBy: "Verified By",
        isInformationCorrect: "Information Correct",
        recommendation: "Recommendation",
        officialName: "Official Name",
        officialDate: "Official Date",
        registrarDate: "Registrar Approval Date",
      },
      assigneeHolders: {
        personnelOfficerById: "Personnel Affairs Officer",
        registrarById: "Registrar/Provost"
      },
      formSections: {
        personalDetails: "Personal Details",
        reason: "Reason for Request",
        nextOfKin: "Next of Kin",
        officialUse: "Official Use Only",
      },
    },
    {
      id: 14,
      name: "Employee Final Disengagement Clearance Form",
      description: "Clearance form for staff disengaging from service",
      status: "Active",
      createdBy: "System",
      lastUpdated: "2025-02-01",
      workflows: ["General Request"],
      component: (props: any) => <EmployeeDisengagementForm {...props} />,
      inputLabels: {
        fileNo: "File No",
        staffName: "Staff Name",
        department: "Department",
        disengagementDate: "Date of Disengagement",
        registrarAuthName: "Registrar Name (Auth)",
      },
      assigneeHolders: {
        storeOfficer: "Store Officer",
        headSalariesWages: "Head (Salaries & Wages)",
        bursar: "Bursar",
        collegeLibrarian: "College Librarian",
        dean: "Dean",
        headDeptUnit: "Head of Department/Unit",
        worksMaintenance: "Works and Maintenance",
        loansAdvances: "Loans & Advances",
        treasurerCoop: "Treasurer (Staff Cooperative Society)",
        treasurerCoeasu: "Treasurer (COEASU)",
        treasurerSsucoen: "Treasurer (SSUCOEN)",
        treasurerNasu: "Treasurer (NASU)",
        treasurerAonnulah: "Treasurer (AONNULAH)",
        treasurerAgape: "Treasurer (AGAPE LOVE)",
        personnelAffairsId: "Personnel Affairs Division",
        chairmanTetfund: "Chairman (TETFund)",
        chairmanAcademicWelfare: "Chairman (ASWS)",
        registrarById: "Registrar"
      },
      formSections: {
        sectionA: "Section A: Details",
        sectionB: "Section B: Clearance",
        sectionC: "Section C: Authority",
      },
    },
    {
      id: 15,
      name: "Promotion Expression of Interest Form",
      description: "Form for staff expression of interest in promotion",
      status: "Active",
      createdBy: "System",
      lastUpdated: "2025-02-01",
      workflows: ["General Request"],
      component: (props: any) => <PromotionInterestForm {...props} />,
      inputLabels: {
        fileNo: "File No",
        surname: "Surname",
        schoolDepartment: "School/Department",
        presentAppointment: "Present Appointment",
        hodName: "HOD Name",
        checkedBy: "Checked By (Personnel)",
      },
      assigneeHolders: {
        departmentHeadById: "HOD/HOU/Immediate Supervisor",
        personnelOfficerById: "Personnel Affairs Officer"
      },
      formSections: {
        personalInfo: "Personal Information",
        endorsement: "Endorsement",
        officialUse: "Official Use Only",
      },
    },
    {
      id: 16,
      name: "Request Form for Change of Next of Kin",
      description: "Form for changing next of kin details",
      status: "Active",
      createdBy: "System",
      lastUpdated: "2025-02-01",
      workflows: ["General Request"],
      component: (props: any) => <ChangeOfNextOfKinForm {...props} />,
      inputLabels: {
        fullName: "Full Name",
        fileNo: "File No",
        department: "Department",
        designation: "Designation",
        authName: "Authenticated By",
      },
      assigneeHolders: {
        personnelOfficerById: "Personnel Authentication"
      },
      formSections: {
        personalDetails: "Personal Details",
        nextOfKin: "Particulars of Next of Kin",
        authentication: "Personnel Authentication",
      },
    },

  ]);

  const addForm = (formData: Omit<FormProps, "id">) => {
    const newForm: FormProps = {
      id: Date.now().toString(),
      ...formData,
    };
    setForms((prevForms) => [...prevForms, newForm]);
  };

  const removeForm = (formId: string | number) => {
    setForms((prevForms) => prevForms.filter((form) => form.id !== formId));
  };

  const updateForm = (formId: string | number, updatedData: Partial<any>) => {
    setForms((prevForms) =>
      prevForms.map((form) =>
        form.id === formId ? { ...form, ...updatedData } : form
      )
    );
  };

  const getFormById = (formId: number) => {
    return forms.find((form) => form.id === Number(formId));
  };

  return {
    forms,
    addForm,
    removeForm,
    updateForm,
    getFormById,
  };
};

export default useForm;
